# Continuos deployment

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

variables:
  AzureSubscriptionId: 'Azure for Students(c6f940ca-9b9f-41e0-8194-16017f517c32)'
  ResourceGroup: 'rg-iw5-2024-project'

stages:
- stage: DeployAPI
  jobs:
  - job: DeployAPI
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          Connect-AzAccount -SubscriptionId "$(AzureSubscriptionId)"

          $AppServiceName = 'app-iw5-2024-team-xkruli03-api'
          $PackagePath = "$(Pipeline.Workspace)/SharpForms.Api.App"

          Publish-AzWebApp -ResourceGroupName "$ResourceGroup" -Name "$AppServiceName" -ArchivePath "$PackagePath"

