# Continuos deployment

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

variables:
  AzureSubscriptionId: 'Azure for Students(c6f940ca-9b9f-41e0-8194-16017f517c32)'
  ResourceGroup: 'rg-iw5-2024-project'
  buildConfiguration: 'Release'
  solution: '**/*.sln'
  outputDir: '$(Pipeline.Workspace)/publish'
  SolutionName: 'SharpForms'
  ProjectAPI: 'SharpForms.Api.App'

stages:
- stage: Build
  jobs:
  - job: BuildApp
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '8.x'

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'
    
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        projects: '$(SolutionName)/$(ProjectAPI)/$(ProjectAPI).csproj'
        arguments: '--configuration $(buildConfiguration) --output $(outputDir)/$(ProjectAPI)'
      displayName: 'Publish $(ProjectAPI)'

    - publish: '$(outputDir)/$(ProjectAPI)'
      artifact: 'artifact.$(ProjectAPI)'


- stage: Deploy
  jobs:
  - job: DeployApp
    steps:
    - download: current
      artifact: 'artifact.$(ProjectAPI)'

    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: '$(AzureSubscriptionId)'
        appType: 'webApp'
        WebAppName: '$app-iw5-2024-team-xkruli03-api'
        ResourceGroupName: '$(ResourceGroup)'
        Package: '$(Pipeline.Workspace)/artifact.$(ProjectAPI)'
