# Continuos deployment

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

variables:
  AzureSubscriptionId: 'Azure for Students(c6f940ca-9b9f-41e0-8194-16017f517c32)'
  ResourceGroup: 'rg-iw5-2024-project'
  buildConfiguration: 'Release'
  solution: '**/*.sln'
  outputDir: '$(Pipeline.Workspace)/publish'
  SolutionName: 'SharpForms'
  ProjectAPI: 'SharpForms.Api.App'
  ProjectWeb: 'SharpForms.Web.App'
  ProjectIdentity: 'SharpForms.IdentityProvider'

stages:
- stage: Build
  jobs:
  - job: BuildApp
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '8.x'

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'
    
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        projects: '**/$(ProjectAPI).csproj'
        arguments: '--configuration $(buildConfiguration) --output $(outputDir)/$(ProjectAPI)'
        publishWebProjects: false
      displayName: 'Publish $(ProjectAPI)'

    - publish: '$(outputDir)/$(ProjectAPI)'
      artifact: 'artifact.$(ProjectAPI)'
      
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        projects: '**/$(ProjectWeb).csproj'
        arguments: '--configuration $(buildConfiguration) --output $(outputDir)/$(ProjectWeb)'
        publishWebProjects: false
      displayName: 'Publish $(ProjectWeb)'

    
    - publish: '$(outputDir)/$(ProjectWeb)'
      artifact: 'artifact.$(ProjectWeb)'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        projects: '**/$(ProjectIdentity).csproj'
        arguments: '--configuration $(buildConfiguration) --output $(outputDir)/$(ProjectIdentity)'
        publishWebProjects: false
      displayName: 'Publish $(ProjectIdentity)'


    - publish: '$(outputDir)/$(ProjectIdentity)'
      artifact: 'artifact.$(ProjectIdentity)'

- stage: Deploy
  jobs:
  - job: DeployApp
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: 'artifact.$(ProjectAPI)'
        path: '$(Pipeline.Workspace)'

    - task: AzureWebApp@1
      inputs:
        azureSubscription: '$(AzureSubscriptionId)'
        appType: 'webApp'
        appName: 'app-iw5-2024-team-xkruli03-api'
        package: '$(Pipeline.Workspace)/**/$(ProjectAPI).zip'
        resourceGroupName: '$(ResourceGroup)'
        deploymentMethod: 'auto'
      displayName: 'Deploy $(ProjectAPI)'
        
    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: 'artifact.$(ProjectWeb)'
        path: '$(Pipeline.Workspace)'
    - task: AzureWebApp@1
      inputs:
        azureSubscription: '$(AzureSubscriptionId)'
        appType: 'webApp'
        appName: 'app-iw5-2024-team-xkruli03-web'
        package: '$(Pipeline.Workspace)/**/$(ProjectWeb).zip'
        resourceGroupName: '$(ResourceGroup)'
        deploymentMethod: 'auto'
      displayName: 'Deploy $(ProjectWeb)'

    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: 'artifact.$(ProjectIdentity)'
        path: '$(Pipeline.Workspace)'
    - task: AzureWebApp@1
      inputs:
        azureSubscription: '$(AzureSubscriptionId)'
        appType: 'webApp'
        appName: 'app-iw5-2024-team-xkruli03-identity'
        package: '$(Pipeline.Workspace)/**/$(ProjectIdentity).zip'
        resourceGroupName: '$(ResourceGroup)'
        deploymentMethod: 'auto'
      displayName: 'Deploy $(ProjectIdentity)'
